### ISSUE TITLE
Display times associated with loot (currently commented out, but otherwise implemented)

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#10]
Just need to uncomment a few lines. I think it's just at the bottom of the Javascript files for loot and roster.

**Comment by Pyrodius0** [comment]
Uncommented the lines that you mentioned, I also added a new line to the header file.. I am not exactly sure this is the best place to put this. But I think having this timestamp on the "Have It" cards is a good approach.
