### ISSUE TITLE
Wishlist item search - no trimming whitespace at the start

### ISSUE THREAD

**Issue by Sentence** [thatsmybis/thatsmybis#101]
**Describe the bug**
While searching items, the starting whitespace(s) seems not to be cropped and can't find the item itself.

**To Reproduce**
1. Go to character's loot > wishlist editing
2. Type " Magtheridon's Head"
3. Can't find the item

**Expected behavior**
Trimming whitespaces at the start, like from the end

**Screenshots**
![image](https://user-images.githubusercontent.com/716852/112140365-33018f80-8bd4-11eb-9b15-caf9579e6079.png)

**Comment by Sentence** [comment]
https://github.com/thatsmybis/thatsmybis/pull/102

**Comment by Sentence** [comment]
#102

**Comment by Lemmings19** [comment]
Suggestion accepted and the some code from your PR has been cherry picked and added to the repo.
