### ISSUE TITLE
Group item assignments into a specific raid or date grouping

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#14]
When assigning loot from a raid, it would be useful to associate that loot with the raid it was received/given in. So if a group clears AQ on Tuesday, August 11th, any loot given during that raid should be linked to that clear.

We don't necessarily have to implement a super-robust page for displaying this relationship in this PR, but we want to at least lay the structure and functionality that would support it.

This one will probably require a bit of planning before implementation.

One catch on the UI side of things is that we'd have to add a way to retroactively assign an item to a past raid. That would probably mean some kind of a lookup for past raids, a new input field, etc. If we add too many input fields beside item entries, things will get cluttered. We might consider collapsing/hiding this new input until the user wants to show it/use it.

**Comment by Pyrodius0** [comment]
Warning: Really poorly drawn example of UI. 

We can add a drop down box and default the raid next to the user on the assign loot page. 

![image](https://user-images.githubusercontent.com/69526309/90720649-dd46bc80-e26b-11ea-82bb-66c2849383b8.png)
