### ISSUE TITLE
New guild members cannot request items once wishlist are locked

### ISSUE THREAD

**Issue by garside** [thatsmybis/thatsmybis#174]
**Is your feature request related to a problem? Please describe.**
We've started raiding so we've locked our wishlists. However, we've also started recruiting. Now, new people join and because wishlists are locked I have to either enter their lists myself manually (eww) or go in and flip on and off the lock so they can savce them themselves (also eww).

**Describe the solution you'd like**
Allow players who have no items saved to their list to create a wishlist even if the list is locked. Seems sensible to me!

Ideally add a configurable grace period. I would love to give new folks who join the guild 24 hours to set their list even with the list being locked otherwise.

**Describe alternatives you've considered**
See above in problem statement for workarounds.

**Additional context**
None

**Comment by Lemmings19** [comment]
I'm not sure if you've already found it, but you can edit an individual member's profile to allow them to edit their wishlists. This came up in Discord (maybe that was you?), so I've added a link to this setting from the character edit page too.
![image](https://user-images.githubusercontent.com/3407841/121968768-c5bf4f80-cd27-11eb-88e4-b69cc66cafc5.png)

**Comment by garside** [comment]
this wasn't me, but thanks! :D
