### ISSUE TITLE
The "excused" option cannot be undone once checked.

### ISSUE THREAD

**Issue by Aggrend** [thatsmybis/thatsmybis#202]
**Describe the bug**
Once someone is marked as "excused" you cannot uncheck that box and give them "credit" for attendance.

**To Reproduce**
1. Create a raid and add a raid team to it.
2. Set one of your raiders to "benched" and check the "excused" box and save the raid.
3. Go back in to edit the raid and uncheck the "excused" box.
4. ---> The raider is still reflected as "excused" and counts as not having attended the raid once you save and exit.

**Expected behavior**
Once you undo the "excused" box, I'd expect the player to be counted as having attended the raid if a relevant reason for sitting such as "benched" is selected.

**Additional context**
Additionally (and this might just be feedback), using the "excused" option says "this wont be counted against attendance". Well, it quite literally does count against it. When I am looking at loot prios, it shows any people that were ever excused from the raid as just not having attended that raid, which drops their participation and could unfairly cause loot issues down the line.

I'd suggest just removing the excused box altogether, rewording the message you recieve when you click it, and/or adding logic associated with the dropdown options to either give credit or not give credit based on the reason for the abscense. Excuse is just generally confusing in its current form.

**Comment by Lemmings19** [comment]
Should be fixed, thanks for reporting!

**Comment by Lemmings19** [comment]
As for excused not working, I'll see if I can reproduce.
