### ISSUE TITLE
Localization of item names

### ISSUE THREAD

**Issue by Ardash** [thatsmybis/thatsmybis#204]
Hello.
I looked at the code and it looks like there it is not very difficult to implement this feature, so there is request.

There is 10 files where you can add language prefix to wowhead address.
Example:
CONCAT('https://{$subdomain}.wowhead.com/item=', items.item_id) AS 'url'
CONCAT('https://{$langConstantWithDot}{$subdomain}.wowhead.com/item=', items.item_id) AS 'url'

**Comment by Lemmings19** [comment]
Do you have any proposals for how best to capture a user's language?

**Comment by Lemmings19** [comment]
Nevermind. [PR created](https://github.com/thatsmybis/thatsmybis/pull/208), just needs testing. Can be tested at http://54.160.171.176/

(uses prod DB, so you can use this with your live guild)

**Comment by Ardash** [comment]
Thanks. It works. My BIS list translated. Big Thanks

**Comment by Lemmings19** [comment]
Note that item lookups aren't translated. I don't have an easy fix for that yet.

**Comment by Ardash** [comment]
>> Note that item lookups aren't translated. I don't have an easy fix for that yet.
All item names stored in DB.
So problem that this request return false.
                $results = Item::select(['name', 'item_id'])
                    ->where([
                        ['name', 'like', '%' . trim($query) . '%'],
                        ['expansion_id', $expansionId],
                    ])

I think you can add more columns for every locale and send current locale in query.

Otherwise, you can extend this list with all localized names in 'name' column, so user can request name in any locale regardless of selected.
