### ISSUE TITLE
Add an indicator as to whether or not a character is an alt

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#24]
Some guilds will want to know if a character is an alt. These guilds typically prioritize mains over alts in many scenarios, and this is especially popular early on in a realm's lifecycle.

This could be done by adding a boolean to the database table for characters, a checkbox when editing a character, and some kind of indicator everywhere that character is displayed.

While I personally believe that this is invalid most of the time, as a character's raid group should be used to determine their eligibility (even if it's an alt, if it belongs to that raid permanently, it should get fair access), I see the arguments for adding this in anyway.

**Comment by Pyrodius0** [comment]
Picked this up as a quick last task of the night. 

I added an indicator to the character tiles to determine if it is an Alt or not. 

Examples: 

Character Creation:
![image](https://user-images.githubusercontent.com/69526309/90478399-f9b6ed80-e0e1-11ea-814d-78542683cafe.png)

Character Update: 
![image](https://user-images.githubusercontent.com/69526309/90478476-0a676380-e0e2-11ea-8b36-2d9980b8f9aa.png)

Character Overview:
![image](https://user-images.githubusercontent.com/69526309/90478529-17845280-e0e2-11ea-9819-119169b8ba3f.png)

Item Wishlist and Have it Section: (Note this highlights another bug.. not in scope of this PR) 
![image](https://user-images.githubusercontent.com/69526309/90478618-3da9f280-e0e2-11ea-9651-04dc02379996.png)

Member's Character Overview:
![image](https://user-images.githubusercontent.com/69526309/90478658-52868600-e0e2-11ea-83da-5d07f2bc5527.png)
