### ISSUE TITLE
Should duplicates be shown on wishlists?

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#259]
Should the overall wishlist view show duplicates? Was this feature previously here, but was removed?

Currently adding one copy of the item will remove all instances of it? [That shouldn't be happening.](https://discord.com/channels/732998376798552210/733019389284188180/898364165813592085) I didn't think this is how that worked... verify this bug?

This has come up at least a few times; probably more.

More details in #293 

![image](https://user-images.githubusercontent.com/3407841/156275525-ee6ae7bd-956a-4c20-ae74-f8cb900528f2.png)

![image](https://user-images.githubusercontent.com/3407841/156275516-fd464755-d3b0-42a0-b168-1b0eb6ea90ad.png)

https://discord.com/channels/732998376798552210/733019346649088121/935400228654313573

https://discord.com/channels/732998376798552210/733019346649088121/927246796026175499

https://discord.com/channels/732998376798552210/732998377339486260/920346924236832818

https://discord.com/channels/732998376798552210/732998377339486260/920346924236832818

Adding one crosses off all:
https://discord.com/channels/732998376798552210/732998377339486260/920360213754806293

**Comment by markus101** [comment]
Rright now if there are multiple of the same item listed on your listed (or in the case of Tier token pieces), multiple of the same token, marking one as received, either via assignment from a Gargul export or manually by a raider results in all instances of the item being received.

I realize this isn't exactly the same as showing them, but in order for things to work correctly both issues would need to be resolved, presumably at the same time, if you'd prefer I can open a separate issue though.

**Comment by Lemmings19** [comment]
Duplicates of wishlist items and received items should now be showing on the prio edit page and instance loot page.
