### ISSUE TITLE
Export - HTML Export Content showing in the browser can't be copied into a Google Spreadsheet - maybe consider text/plain mime type

### ISSUE THREAD

**Issue by suetterp** [thatsmybis/thatsmybis#279]
Hi [Lemmings19](https://github.com/Lemmings19),

I saw that in ExportController.php the following types of output formats can be choosen: **json, html or csv**.

In order to **copy the content from the browser screen to the clipboard** the html feature is very handy since it immediatly shows the CSV content on screen instead of dropping a file.

When using one of the applications export endpoint - e.g. https://thatsmybis.com/6852/trinitat-lakeshire/export/raid-groups/html it seems to be not possible to simply paste the clipboard content e.g. into a Google Spreadsheet. 

When reading the error message is appears that all the text seems to be squeezed into a sigle cell.
I assume it may be because the HTTP Body content type is HTML and the CSV text is enclosed in a <span ..>[CSV_STRING_HTML_ENCODED]<\/span> element when looking at the payload sent by the server in the response body.

There is also a easy workaround atm.:
1.) CTRL+V all content from the clipboard into a texteditor such as the Microsoft Windows Editor
2.) CTRL+A / CTRL+C the previously pasted text in the editor and finally it can be successfully pasted into the spreadsheet.

So my request would be:

Would it be maybe possible to add an extra fileType variant for e.g. 'plaintext' besides the existing feautre for HTML export ?
response($csv) ->withHeaders(['Content-Type' => 'text/plain' . . . .

Maybe even the default 'guild.export.generic' export could be replaced with the pure plaintext export - if people are copying from it could be maybe even safer for later use of the data in all external tools consuming data from there.

![image](https://user-images.githubusercontent.com/34806030/156933832-d0fbb60c-9e7c-4cc1-b205-a7f2ad7a6a04.png)

**Comment by Lemmings19** [comment]
I don't check these tickets terribly often.

I switched to: (as suggested)
```
'X-Content-Type-Options' => 'nosniff',
'Content-Type'           => 'text/plain',
'Cache-Control'          => 'no-store, no-cache',
```
So now the content should display in a format that can be copied into Excel/Sheets while preserving newlines.
![image](https://user-images.githubusercontent.com/3407841/200923530-2ad77c91-79f8-4bdf-b0c5-b1b13b74bcc8.png)
