### ISSUE TITLE
HTML "All" export does not include items not part of loot tables

### ISSUE THREAD

**Issue by mmolignano** [thatsmybis/thatsmybis#280]
We have additional guild prio and guild notes for items that are not necessarily part of loot tables but are crafted versions of the patterns that drop.

For example:

Pattern: https://tbc.wowhead.com/item=35194/schematic-surestrike-goggles-v3-0
Crafted Item: https://tbc.wowhead.com/item=34356/surestrike-goggles-v3-0

When I do an export for "All" data (i.e. https://thatsmybis.com/_...guildnumber..._/_...guildname..._/export/loot/html/all) I would hope to see any comments added to any items so that they appear in tooltips for those items.

**Comment by Lemmings19** [comment]
Should be fixed now. I don't check these tickets very often.
