### ISSUE TITLE
Loot > Notes > Naxx N10 -> cause a 500

### ISSUE THREAD

**Issue by mbernard** [thatsmybis/thatsmybis#281]
**Describe the bug**
Notes on Naxx N10, cause a 500

**To Reproduce**
1. Loot
2. Notes
3. Naxx N10

**Expected behavior**
no error :P

**Screenshots**
![image](https://user-images.githubusercontent.com/1928530/187493750-5a78e7c8-bdf2-4bb7-81e4-616f28b7b014.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Comment by Lemmings19** [comment]
Are you still receiving this error? If so, what is the name of the Discord account tied to your TMB account (so that I can view the notes for your guild to help debug).

I am not seeing the error on my end.

I also don't check github notifications very often.

**Comment by mbernard** [comment]
Nope all good now. It's been fixed a few days after the release of WOTLK.
I'll close the bug, sorry I forgot
