### ISSUE TITLE
Bad wowhead link

### ISSUE THREAD

**Issue by Boxcar87** [thatsmybis/thatsmybis#282]
WotLK items are using generic wowhead url

https://github.com/thatsmybis/thatsmybis/blob/5f61baedbb27a1f23d855cee9f6f2ce0404e1dc6/public/js/autocomplete.js#L311-L323

**Comment by Lemmings19** [comment]
I am guessing wowhead went ahead and supported the old link structure for wotlk; hence why this issue hasn't come up recently. In any event, I've corrected the structure of the url to match `wowhead.com/wotlk` instead of `wotlk.wowhead.com`.

Cheers.
