### ISSUE TITLE
There Are Two Heroic Key to the Focusing Iris Items 

### ISSUE THREAD

**Issue by WillowGryph** [thatsmybis/thatsmybis#286]
Both are quest items for neck pieces but I'm unsure which one to use to help my loot council out.

![image](https://user-images.githubusercontent.com/113316179/194156634-38eb4170-682c-43b4-b706-d5fe8daf029d.png)

**Comment by Jakobud** [comment]
Probably because one is for Alliance and one is for Horde since they start a quest. I'm not sure how to resolve that except that TMB needs to only show items that are visible to Horde/Alliance depending on what faction the guild is.

**Comment by BreakBB** [comment]
No the reason for this, is that there is the item that starts the quest: https://www.wowhead.com/wotlk/item=44577/heroic-key-to-the-focusing-iris

And the actual key you receive has the same name: https://www.wowhead.com/wotlk/item=44581/heroic-key-to-the-focusing-iris
