### ISSUE TITLE
Show ranking/list of the amount of loot received

### ISSUE THREAD

**Issue by BreakBB** [thatsmybis/thatsmybis#288]
**Is your feature request related to a problem? Please describe.**

Our loot council also considers the amount of loot received by players so far. We know we can check on every player to see how many items he received, but it would be great to get simple overview about the amount the players of a Raid Group received in the past.

**Describe the solution you'd like**

A simple ranking/list about how many items each player of a Raid Group received.

Like

> Player A: 4 (2 OS)
> Player B: 2 (0 OS)
> ...

**Describe alternatives you've considered**
Instead of a list a graph in some sort would also help

**Additional context**

**Comment by Lemmings19** [comment]
Does the "stats" page solve your problem?
![image](https://user-images.githubusercontent.com/3407841/196271323-62225f18-6bff-4bbb-9c9d-db5157dc4e6c.png)

**Comment by BreakBB** [comment]
Hey @Lemmings19 I just found out about this page myself. Yes, thank you very much, that does exactly what we needed! ❤️
