### ISSUE TITLE
Officer notes can't always be set to null

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#29]
Performing the check `if ($currentMember->hasPermission('edit.officer-notes') && request()->input('officer_note'))` will return false if the officer note is empty, and it won't actually update the value.

Check to make sure there aren't any other problems preventing the note from being nulled out.

**Comment by Lemmings19** [comment]
https://github.com/thatsmybis/thatsmybis/blob/master/app/Http/Controllers/CharacterController.php#L494

Someone trying to update a public note (while leaving officer note blank) is hitting this and getting the wrong result. Fix.

**Comment by Pyrodius0** [comment]
This is a pretty quick fix.

request()->input('officer_note') doesnt really need to even be in this line. 

If it is populated, we are always going to update the field. If it is not populated, its null so we just assign that value which lets us null it out.
