### ISSUE TITLE
Prio order number does not decrease when an item is received by a character

### ISSUE THREAD

**Issue by Jakobud** [thatsmybis/thatsmybis#291]
**Describe the bug**
If you have multiple characters on a prio list for an item like this:

Mantle of Lost Protector
1. John
2. Bob
3. Alex
4. Jeff

After John receives the item, John is removed from the list but now the list looks like this:

2. Bob
3. Alex
4. Jeff

**To Reproduce**
1. Award an item to a character and noticed that subsequent character prio numbers does not decrease

**Expected behavior**
The new list should look like this:
1. Bob
2. Alex
3. Jeff

**Additional context**
It's important that these numbers change because currently it's impossible to tell how many items a character is first-in-line for on the roster page. If a character is 1st in line for several items then you can safely assume they are 1st in line for those items. But if the page also shows they are 2nd, 4th, 8th, 15th in line for other items in their prio list, some of those items they may also be 1st in line for because the prio number (above) did not decrease as other characters have received those items.

It can make the roster prio lists very misleading and not really useful at all if the number next to each item is not an accurate representation of how many other characters are in line before them.

**Comment by Lemmings19** [comment]
This behaviour was initially intentional, but I can see that for many guilds this behaviour isn't desired. I will see about adding in a mode to recalculate the prio numbering.

**Comment by Lemmings19** [comment]
This should be working as expected now.

One caveat: The system will reduce the rank of all remaining prios by 1. If there is a rank that is skipped, the system will not account for this (the list isn't completely recalculated; I took a lazier approach).

eg.
- Ranks are: 1, 2, 5, 6, 7
- 1 is assigned.
- Ranks are now: 2, 4, 5, 6
