### ISSUE TITLE
"Hide OS" button should hide all received OS items on the Stats page

### ISSUE THREAD

**Issue by BreakBB** [thatsmybis/thatsmybis#292]
**Is your feature request related to a problem? Please describe.**
The button "Hide OS" currently only hides the OS items, when "Show all loot" is active. But it does not change the numbers of the received items.

**Describe the solution you'd like**
It would be nice if that button would also update the numbers indicating the amount of items received.

**Comment by Lemmings19** [comment]
The page was a quick (and incomplete) feature put together some time ago. I've updated it to work as people would expect, and fixed a number of bugs.
