### ISSUE TITLE
Archived characters' items are still appearing in the TMB Tooltips exports

### ISSUE THREAD

**Issue by yvigeant** [thatsmybis/thatsmybis#294]
**Describe the bug**
When using the Guild -> Export TMB Tooltips feature, the export still contains items for archived characters (prios, wishlists, received).

**To Reproduce**
1. Assign a prio item to a character
2. Archive the character
3. Click on Guild -> Export TMB Tooltips
4. Search for the archived character's name.

**Expected behavior**
Archived characters items should not appear in the export.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 106.0.5249.103

**Comment by Lemmings19** [comment]
Should be fixed, thank you for reporting.
