### ISSUE TITLE
Stat Totals Not Updating With Filters Selected

### ISSUE THREAD

**Issue by Kdcargill** [thatsmybis/thatsmybis#295]
**Describe the bug**
When you go to the Stats page under Roster and put in filters, none of the numbers update for the columns.

**To Reproduce**
1. Go to Roster
2. Move down to Stats and click
3. Input item filters (ex. Nax 25, EoE25, OS25)
4. You can also click hide OS and the totals do not update either

**Expected behavior**
The expected behavior is for all totals for all columns to update depending on what filters you have turned on as well as the show all loot filter to have that same behavior with update totals.

**Screenshots**
I could take screenshots but it seems kind of pointless

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 106.0.5249.120

**Additional context**

**Comment by Lemmings19** [comment]
The page was a quick (and incomplete) feature put together some time ago. I've updated it to work as people would expect, and fixed a number of bugs.
