### ISSUE TITLE
Show what rank someone's wishlist item is on the item list page

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#30]
This should be pretty simple as the value is stored alongside the item in the `character_items` table in the column `order`. The harder part will be coming up with a good way to add it to the UI without it looking messy/distracting. Maybe a muted colour that blends in and will only be noticed if you look a little harder.

This is a good first issue because it should only require editing a bit of javascript. Possibly modifying the columns selected in a query, _possibly_ joining a new table in a query. (if you're having difficulty finding the value, check the parameter/array/value/child labelled 'pivot' if it exists)

**Comment by fiorenza** [comment]
Hello.

Can I help you with this issue? I have forked the project, but I have a problem with configs of Discord.

Can you help me with this problem?

`{
  "client_id": [
    "Value \"\" is not snowflake."
  ]
}`

Looking the project I can see that I don't have the enviroments configurations for Discord, how can I get this configurations?

**Comment by Lemmings19** [comment]
@fiorenza this issue is not the place to ask this question. You can create an application and a bot on Discord to get these values: https://discord.com/developers/applications

If you'd like to ask any other questions, please followup on Discord. This project's Discord is https://discord.gg/HWNUMKK

**Comment by Lemmings19** [comment]
@fiorenza Sorry, I misread your comment and thought that you were just looking for help getting the environment setup in your fork. I completely overlooked that you were looking to contribute for this specific issue.

Yes, you can help with this issue if you are still interested. I would still like to direct you to this project's [Discord server[(https://discord.gg/HWNUMKK) where I can give you the contributor tag and better help you get your environment setup.

(I just happened to spot this as I was reviewing open issues)

**Comment by Lemmings19** [comment]
Upon review, it appears that this issue has already been resolved last month.
