### ISSUE TITLE
Rather than removing an item from a wishlist when it is assigned, toggle that item as 'received' and leave it in the wishlist.

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#49]
It would be nice if items received were left on the wishlist, but ~~striked out~~.

Add a flag to the wishlist item. Hide that wishlist item throughout the site, but still display it when viewing the character, just with a strikethrough.

However, this would also preserve the user's old wishlist ordering. It doesn't make sense to me that the majority of users on the website would like for their old wishlist ordering to be preserved. If their top item is received, their second item should now become their top prio.

Figure out what the solution to this should be before implementing.

Original request: https://discordapp.com/channels/732998376798552210/733019346649088121/751108835795796018

**Comment by nilithu** [comment]
I guess quite a few guilds would like to see this implemented. Our loot council actually takes the priorities into account when distributing loot. If someone puts an item on priority 1 he is more entitled to it than someone who has the same item on priority 5. 

It might actually make sense to add a new "settings" page in the admin area where certain features can be enabled?!  

In addition a new boolean flag would be needed and depending of its value the logic of the current queries should be extended to filter for `Item::TYPE_WISHLIST` and `Item::TYPE_RECEIVED` if the flag is set to true. It also would require to pass the type of an item to the view and strike it out if it is of type `Item::TYPE_RECEIVED`
