### ISSUE TITLE
Freeze Column Header Row for Loot and Roster screens

### ISSUE THREAD

**Issue by CrewBlackangus** [thatsmybis/thatsmybis#50]
When scrolling through the Loot and Roster screens, the Column Header row gets lost.

![image](https://user-images.githubusercontent.com/70775382/92277185-46067980-eea7-11ea-8c93-93607e554513.png)

Would be nice to freeze it similar to how you can in MS Excel.

**Comment by Lemmings19** [comment]
For anyone looking to implement this, the following documentation is likely a good place to start: https://datatables.net/extensions/fixedheader/

**Comment by Lemmings19** [comment]
https://github.com/thatsmybis/thatsmybis/commit/336775599a64ab4508a98bb24954268193ddc8e8
